// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vojyhzslkiegusccynmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvanloenNsa2llZ3VzY2N5bm1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjgyMjUsImV4cCI6MjA2ODEwNDIyNX0.n4Psyo_TIByJmU9yFcIpQP7h5z75O-xDvcBZEXLjNec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});